#!/bin/sh
### BEGIN INIT INFO
# Provides:          mcp
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:
# Short-Description: Provides the simulated MCP service
# Description:       Provides the simulated service
### END INIT INFO

NAME=mcp
DAEMON=/opt/mcp/bin/mcp
PIDDIR=/var/run
PIDFILE=$PIDDIR/mcp.pid
DAEMONUSER=root
PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

mcp_start () {
	log_daemon_msg "Simulated starting system $NAME Daemon"
}

mcp_reload () {
	log_daemon_msg "Simulated reloading system $NAME Daemon"
}

mcp_stop () {
	log_daemon_msg "Simulated Stopping system $NAME Daemon"
}

case "$1" in
	start|stop|reload)
		mcp_${1}
		;;
	restart)
		mcp_stop
		mcp_start
		;;
	*)
		echo "Usage: /etc/init.d/mcp {start|stop|estart|reload}"
		exit 1
		;;
esac

exit 0
