#!/bin/sh
### BEGIN INIT INFO
# Provides:          db_command_processing
# Required-Start:    $local_fs $network mysql
# Required-Stop:     $local_fs $network mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: DB Command Processing Service
# Description:       DB Command Processing Service
### END INIT INFO

NAME=db_command_processing
PROG=command_processing.py
DAEMON=/opt/qs/bin/$PROG
PIDDIR=/var/run
PIDFILE=$PIDDIR/db_command_processing.pid
DAEMONUSER=root
PATH=/sbin:/bin:/usr/sbin:/usr/bin
ARGS='-- --mcp-address=192.168.1.198 --mcp-username=mirage --mcp-password=mirage --domu-ip-range=200'

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

db_command_processing_start () {
	log_daemon_msg "Starting system $NAME Daemon"
	if [ ! -d $PIDDIR ]; then
		mkdir -p $PIDDIR
		chown $DAEMONUSER:$DAEMONUSER $PIDDIR
	fi
	start-stop-daemon -x $DAEMON -p $PIDFILE --make-pidfile --start --background $ARGS
	status=$?
	log_end_msg ${status}
}

db_command_processing_stop() {
	log_daemon_msg "Stopping system $NAME Daemon"
	start-stop-daemon -p $PIDFILE --stop --retry 5 || echo -n "...which is not running"
	status=$?
	log_end_msg ${status}
	if [ ! -f $PIDFILE ]; then
        rm -f $PIDFILE
    fi
}

case "$1" in
	start|stop)
		db_command_processing_${1}
		;;
	restart)
		if [ -s $PIDFILE ] && kill -0 $(cat $PIDFILE) >/dev/null 2>&1; then
			db_command_processing_stop
			db_command_processing_start
		fi
		;;
	force-stop)
		db_command_processing_stop
		sudo pkill $PROG || true
		sleep 2
		sudo pkill -9 $PROG || true
		;;
	status)
		status_of_proc -p $PIDFILE "$DAEMON" "system-wide $NAME" && exit 0 || exit $?
		;;
	*)
		echo "Usage: /etc/init.d/db_command_processing {start|stop|force-stop|restart|status}"
		exit 1
		;;
esac

exit 0
